---
- name: update yum 
  yum:
    name: '*'
    state: latest
- name: epel-release repo
  yum:
    name: epel-release
    state: latest
- name: install java 1.8
  yum:
    #name: java-1.8.0-openjdk-devel
    name: java-11-openjdk-devel
    state: latest

- name: check java exists 
  #stat: path=/usr/lib/jvm/jre-1.8.0-openjdk
  stat: path=/usr/lib/jvm/jre-11-openjdk
  register: java_path

- name: add java path in profile
  #command: echo -e "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk" >> /etc/profile
  command: echo -e "export JAVA_HOME=/usr/lib/jvm/jre-11-openjdk" >> /etc/profile
  when: java_path.stat.exists

- name: check jre exists
  stat: path=/usr/lib/jvm/jre
  register: jre_path

- name: add jre path in profile 
  command: echo -e "export JAVA_HOME=/usr/lib/jvm/jre" >> /etc/profile
  when: jre_path.stat.exists


